models/Comentario.php
<?php

namespace app\models;

use app\models\ComentarioQuery;
use app\models\Seguridad;
use Yii;

/**
 * This is the model class for table "comentario".
 *
 * @property int $id
 * @property string $nombre
 * @property string $correo
 * @property string|null $web
 * @property string|null $rel
 * @property string $comentario
 * @property string $fecha
 * @property int $articulo_id
 * @property int $estado
 * @property string|null $ip
 * @property string|null $puerto
 *
 * @property Articulo $articulo
 */
class Comentario extends \yii\db\ActiveRecord
{
    const ESTADO_ACTIVO = 1;
    const ESTADO_INACTIVO = 0;
    public $verifyCode;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'comentario';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'comentario', 'fecha', 'articulo_id'], 'required'],
            [['comentario'], 'string'],
            [['fecha'], 'safe'],
            [['articulo_id', 'estado'], 'integer'],
            [['nombre'], 'string', 'max' => 150],
            [['correo', 'web'], 'string', 'max' => 100],
            ['web', 'url', 'defaultScheme' => 'http', 'message' => 'Por favor introduzca la URL completa, ej: www.blonder413.com'],
            [['rel'], 'string', 'max' => 20],
            [['ip'], 'string', 'max' => 15],
            [['puerto'], 'string', 'max' => 5],
            [['verifyCode'], 'captcha', 'on'=>'comentar'],
            [['estado'], 'default', 'value' => self::ESTADO_INACTIVO],
            [['articulo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Articulo::className(), 'targetAttribute' => ['articulo_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'            => 'ID',
            'nombre'        => 'Nombre',
            'correo'        => 'Correo',
            'web'           => 'Web',
            'rel'           => 'Rel',
            'comentario'    => 'Comentario',
            'fecha'         => 'Fecha',
            'articulo_id'   => 'Artículo',
            'estado'        => 'Estado',
            'ip'            => 'Ip',
            'puerto'        => 'Puerto',
        ];
    }
    
    /**
     * {@inheritdoc}
     */
    public function beforeSave($insert)
    {
        /*
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->correo = Seguridad::encriptar($this->correo);
            }
            return true;
        }
        */
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->correo = Seguridad::encriptar($this->correo);
            }
            return true;
        } else {
            return false;
        }
    }
    
    /**
     * {@inheritdoc}
     */
    public static function find()
    {
        return new ComentarioQuery(get_called_class());
    }

    /**
     * Gets query for [[Articulo]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArticulo()
    {
        return $this->hasOne(Articulo::className(), ['id' => 'articulo_id']);
    }
}

controllers/ComentarioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comentario;
use app\models\ComentarioSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * ComentarioController implements the CRUD actions for Comentario model.
 */
class ComentarioController extends Controller
{
    public $layout = 'adminLTE3/main';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
//                'only' => ['index', 'view', 'create', 'delete','update', 'approve'],
                'rules' => [
//                    [
//                        'allow' => true,
//                        'actions' => ['index'],
//                        'roles' => ['?'],
//                    ],
                    [
                        'allow' => true,
                        'actions' => [
                            'index', 'index-ajax', 'view', 'create', 'update', 
                            'delete', 'aprobar'
                        ],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comentario models.
     * @return mixed
     */
    public function actionIndex()
    {
        if ( !\Yii::$app->user->can('comentario-listar')) {
            throw new ForbiddenHttpException();
        }
        
        $searchModel = new ComentarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $pendientes = Comentario::find('status = 0')->count();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pendientes'    => $pendientes,
        ]);
    }
    
    /**
     * Lista todos los comentarios
     * @return mixed
     */
    public function actionIndexAjax()
    {
        if ( !\Yii::$app->user->can('comentario-listar')) {
            throw new ForbiddenHttpException();
        }
        
        $searchModel = new ComentarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//        $pendientes = Comentario::find('estado = 0')->count();
        $pendientes = 0;
        return $this->renderAjax('_index', [
            'searchModel'   => $searchModel,
            'dataProvider'  => $dataProvider,
            'pendientes'    => $pendientes,
        ]);
    }
    
    /**
     * cambia el estado a ACTIVO
     * @return mixed
     */
    public function actionAprobar($id)
    {
        if ( !\Yii::$app->user->can('comentario-cambiar-estado')) {
            throw new ForbiddenHttpException();
        }
        
        $comentario = Comentario::findOne($id);
        
        $comentario->estado = Comentario::ESTADO_ACTIVO;
        
        if ($comentario->save()) {
          Yii::$app->session->setFlash("success", "Comentario aprobado exitosamente!");
        } else {
            $errors = '';
            foreach ($comentario->getErrors() as $key => $value) {
                foreach ($value as $row => $field) {
                    $errors .= $field . "<br>";
                }
            }

            Yii::$app->session->setFlash("danger", $errors);
        }
        return $this->redirect(['index']);
    }

    /**
     * Displays a single Comentario model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if ( !\Yii::$app->user->can('comentario-ver')) {
            throw new ForbiddenHttpException();
        }
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comentario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if ( !\Yii::$app->user->can('comentario-crear')) {
            throw new ForbiddenHttpException();
        }
        
        $model = new Comentario();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                    Yii::$app->session->setFlash("success","Registro $model->id creado satisfactoriamente!");
            } else {
                $errors = '';
                foreach ($model->getErrors() as $key => $value) {
                    foreach ($value as $row => $field) {
                        $errors .= $field . "<br>";
                    }
                }
                Yii::$app->session->setFlash("danger", $errors);    
            }
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Comentario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if ( !\Yii::$app->user->can('comentario-actualizar')) {
            throw new ForbiddenHttpException();
        }
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
        
            if ($model->save()) {
                Yii::$app->session->setFlash("success","Registro $model->id actualizado satisfactoriamente!");
            } else {
                $errors = '';
                foreach ($model->getErrors() as $key => $value) {
                    foreach ($value as $row => $field) {
                        $errors .= $field . "<br>";
                    }
                }
                Yii::$app->session->setFlash("danger", $errors);
            }
        
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Comentario model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if ( !\Yii::$app->user->can('comentario-borrar')) {
            throw new ForbiddenHttpException();
        }
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comentario model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comentario the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comentario::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/comentario/_form.php
<?php
use yii\captcha\Captcha;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Comentario */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comentario-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'correo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'web')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'comentario')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
        'options'   => ['autocomplete' => 'off'],
        'template' => '<div class="row"><div class="col-md-12">{image}</div><div class="col-md-12">{input}</div></div>',
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('<i class="fas fa-comment-alt"></i> Comentar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/comentario/_index.php
<?php
use app\models\Comentario;
use app\models\Seguridad;
use kartik\date\DatePicker;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;

$this->title =  Html::encode( '(' . $pendientes . ') Comentarios');

echo "Última actualización a las " . date("g:i:s a");

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
//            'id',
        'nombre',
        [
            'attribute' => 'correo',
            'format' => 'email',
            'value' => function ($searchModel) {
                return Seguridad::desencriptar($searchModel->correo);
            }
        ],
        'web:url',
//        'rel',
        'comentario:ntext',
//        [
//            'attribute' => 'fecha',
//            'format' => ['date', 'php:D d M Y g:i:s a'],
//        ],
        [
            'attribute' => 'fecha',
            'filter'    => DatePicker::widget([
                'model' => $searchModel, 
                'attribute' => 'fecha',
//                'type' => DatePicker::TYPE_BUTTON,
                'options' => ['placeholder' => 'Seleccione una fecha ...'],
                'pluginOptions' => [
                    'autoclose'=> true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]),
            'format'    => 'datetime',
        ],
        [
            'attribute' => 'articulo_id',
            'format' => 'raw',
            'value' => function ($searchModel) {
                return Html::a(
                    $searchModel->articulo->titulo, 
                    "@web/articulo/" . $searchModel->articulo->slug
                );
            },
            'filter' => Select2::widget([
                'model' => $searchModel,
                'attribute' => 'articulo_id',
                'initValueText' => $searchModel->articulo_id != '' ? $searchModel->articulo->titulo : '',
                'options' => ['placeholder' => 'Busque el artículo'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 3,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Cargando Resultados...'; }"),
                    ],
                    'ajax' => [
                        'url' => Url::to(['articulos/buscar']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function(articulo) { return articulo.text; }'),
                    'templateSelection' => new JsExpression('function (articulo) { return articulo.text; }'),
                ],
            ]),
        //'options' => ['width' => '10%'],
        ],
        /*
        [
            'attribute' => 'estado',
            'filter' => Select2::widget([
                'model' => $searchModel,
                'attribute' => 'estado',
                'value' => $searchModel->estado,
                'data' => [0 => 'INACTIVO', 1 => 'ACTIVO'],
                'options' => ['multiple' => false, 'placeholder' => 'Seleccione ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]),
            'format' => 'raw',
            'value' => function($searchModel) {
                if ($searchModel->estado === Comentario::ESTADO_INACTIVO) {
                    return "<span class='glyphicon glyphicon-remove'></span>";
                } else {
                    return "<span class='glyphicon glyphicon-ok'></span>";
                }
            }
        ],
        */
        //'ip',
        //'puerto',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete} {aprobar}',
            'buttons' => [
                'aprobar' => function ($url, $model, $key) {
                    if ($model->estado == Comentario::ESTADO_INACTIVO) {
                        return Html::a(
                            '<i class="far fa-thumbs-up"></i>',
                            $url,
                            [
                                'class' => 'btn btn-success',
                                'title' => Yii::t('app', 'Aprobar comentario'),
                            ]
                        );
                    }
                },
                'delete' => function ($url, $model) {
                    return Html::a(
                        "<i class='fas fa-trash' aria-hidden='true'></i>",
                        ["delete", "id" => $model->id], 
                        [
                            'class' => 'btn btn-danger',
                            'title' => 'Eliminar',
                            'data-method'   => 'POST',
                            'data-confirm'  => 'Desea eliminar este registro?',
                        ]
                    );
                },
                'update' => function ($url, $model, $key) {
                    return Html::a(
                        '<i class="fas fa-pen"></i>',
                        $url,
                        [
                            'class' => 'btn btn-primary',
                            'title' => Yii::t('app', 'Actualizar'),
                        ]
                    );
                }
            ],
            'urlCreator' => function ($action, $model, $key, $index) {
                if ($action === 'aprobar') {
                    return yii\helpers\Url::to(['comentario/aprobar', 'id' => $key]);
                } elseif ($action == 'update') {
                    return yii\helpers\Url::to(['comentario/update/', 'id' => $key]);
                } elseif ($action === 'delete') {
                    return yii\helpers\Url::to(['comentario/delete/', 'id' => $key]);
                }
            }
        ],
    ],
    'export' => [
        'label' => 'Exportar',
        'messages' => [
            'confirmDownload' => 'De acuerdo para proceder',
        ],
//            'showConfirmAlert'  => false,
    ],
    'exportConfig' => [
//            GridView::HTML => [
//            ],
        GridView::CSV => [
        ],
//            GridView::TEXT => [
//            ],
        GridView::EXCEL => [
            'label' => ( 'XLS'),
            'iconOptions' => ['class' => 'text-success'],
            'showHeader' => true,
            'showPageSummary' => true,
            'showFooter' => true,
            'showCaption' => true,
            'filename' => ('archivoDeBlonder413'),
            'alertMsg' => ( 'El archivo de excel se va descargar.'),
            'options' => ['title' => ( 'Excel')],
            'mime' => 'application/vnd.ms-excel',
            'config' => [
                'worksheet' => ( 'ExportWorksheet'),
                'cssFile' => '',
            ]
        ],
        GridView::PDF => [
        ],
//            GridView::JSON => [
//            ],
    ],
    'hover' => true,
    'toolbar' => [
        '{toggleData}',
        '{export}',
    ],
    'toggleDataContainer' => ['class' => 'btn-group mr-2'],
    'responsive' => true,
    'rowOptions' => function($model) {
        if (!$model->estado) {
            return ['class' => 'danger'];
        } else {
            return ['class' => 'success'];
        }
    },
    'panel' => [
        'after' => Html::a('<i class="fas fa-redo"></i> Limpiar Tabla', ['index'], ['class' => 'btn btn-info']),
//        'before' => Html::a('<i class="glyphicon glyphicon-plus"></i> Crear', ['create'], ['class' => 'btn btn-success']),
        'heading' => 'Administrar Comentario',
        'type' => GridView::TYPE_SUCCESS,
    ],
]);

views/comentario/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ComentarioSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comentario-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'correo') ?>

    <?= $form->field($model, 'web') ?>

    <?= $form->field($model, 'rel') ?>

    <?php // echo $form->field($model, 'comentario') ?>

    <?php // echo $form->field($model, 'fecha') ?>

    <?php // echo $form->field($model, 'articulo_id') ?>

    <?php // echo $form->field($model, 'estado') ?>

    <?php // echo $form->field($model, 'ip') ?>

    <?php // echo $form->field($model, 'puerto') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/comentario/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Comentario */

$this->title = 'Crear Comentario';
$this->params['breadcrumbs'][] = ['label' => 'Comentarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="comentario-create">

    <div class='panel panel-warning'>
        <div class='panel-heading'>
            <h4><?= Html::encode($this->title) ?></h4>
        </div>
        <div class='panel-body'>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

views/comentario/index.php
<?php
use app\models\Comentario;
use app\models\Seguridad;
use kartik\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ComentarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Comentarios';
$this->params['breadcrumbs'][] = $this->title;
$ruta = Yii::$app->homeUrl . 'comentario/index-ajax';

$script = <<< JS
$(document).ready(function() {
//    setInterval(function() {
//      $.pjax.reload({container:'#result_ajax'});
//    }, 450000);
    setInterval(function() {
//        var id = $("#id").val();
        var pendientes = $pendientes;
        $("#resultado_ajax").load("$ruta",{pendientes:pendientes},function(){});
    }, 1000 * 60 * 1); // 1000ms * 60seg * 10min = 10min
});
JS;
$this->registerJs($script);
?>
<div class="comentario-index box box-primary">
    
    <div class="box-body table-responsive no-padding">

    <?php Pjax::begin(); ?>
        <div id="resultado_ajax">
            <!-- Muestro algo cuando carga la página por primera vez -->
            <?php $pendientes = Comentario::find()->where(['estado' => Comentario::ESTADO_INACTIVO])->count(); ?>
            <?= $this->renderAjax('_index',
                [
                    'searchModel'   => $searchModel,
                    'dataProvider'  => $dataProvider,
                    'pendientes'    => $pendientes,
                ], null
            ); ?>
            <!-- /Muestro algo cuando carga la página por primera vez -->
        </div>
    <?php Pjax::end(); ?>
    
    </div>

</div>

views/comentario/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Comentario */

$this->title = 'Actualizar Comentario: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Comentarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="comentario-update">

    <div class='panel panel-warning'>
        <div class='panel-heading'>
            <h4><?= Html::encode($this->title) ?></h4>
        </div>
        <div class='panel-body'>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

views/comentario/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Comentario */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Comentarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="comentario-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Seguro quiere eliminar este elemento?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'correo',
            'web',
            'rel',
            'comentario:ntext',
            'fecha',
            'articulo_id',
            'estado',
            'ip',
            'puerto',
        ],
    ]) ?>

</div>