models/Articulo.php
<?php

namespace app\models;

use app\models\MiActiveRecord;
use yii\behaviors\SluggableBehavior;
use yii\db\Expression;
use yii\helpers\BaseUrl;

use Yii;

/**
 * This is the model class for table "articulo".
 *
 * @property int $id
 * @property int|null $numero
 * @property string $titulo
 * @property string $slug
 * @property string|null $tema
 * @property string $detalle
 * @property string $resumen
 * @property string|null $video
 * @property string|null $descarga
 * @property int $categoria_id
 * @property string $etiquetas
 * @property int $estado
 * @property int $vistas
 * @property int $descargas
 * @property int|null $curso_id
 * @property int $usuario_crea
 * @property string $fecha_crea
 * @property int $usuario_modifica
 * @property string $fecha_modifica
 *
 * @property Categoria $categoria
 * @property Curso $curso
 * @property User $usuarioCrea
 * @property User $usuarioModifica
 * @property Comentario[] $comentarios
 */
class Articulo extends MiActiveRecord
{
    const ESTADO_INACTIVO = 0; // 0
    const ESTADO_ACTIVO = 1;   // 1
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'articulo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['numero', 'categoria_id', 'estado', 'vistas', 'descargas', 'curso_id', 'usuario_crea', 'usuario_modifica'], 'integer'],
            [['titulo', 'detalle', 'video', 'categoria_id', 'etiquetas'], 'required'],
            [['detalle'], 'string'],
            [['fecha_crea', 'fecha_modifica'], 'safe'],
            [['titulo', 'slug'], 'string', 'max' => 150],
            [['tema', 'descarga'], 'string', 'max' => 100],
            [['resumen'], 'string', 'max' => 300],
            [['video', 'etiquetas'], 'string', 'max' => 255],
            [['titulo'], 'unique'],
            [['slug'], 'unique'],
            [['estado'], 'default', 'value' => self::ESTADO_ACTIVO],
            [['categoria_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categoria::className(), 'targetAttribute' => ['categoria_id' => 'id']],
            [['curso_id'], 'exist', 'skipOnError' => true, 'targetClass' => Curso::className(), 'targetAttribute' => ['curso_id' => 'id']],
            [['usuario_crea'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['usuario_crea' => 'id']],
            [['usuario_modifica'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['usuario_modifica' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'                => 'ID',
            'numero'            => 'Numero',
            'titulo'            => 'Título',
            'slug'              => 'Slug',
            'tema'              => 'Tema',
            'detalle'           => 'Detalle',
            'resumen'           => 'Resumen',
            'video'             => 'Video',
            'descarga'          => 'Descarga',
            'categoria_id'      => 'Categoría',
            'etiquetas'         => 'Etiquetas',
            'estado'            => 'Estado',
            'vistas'            => 'Vistas',
            'descargas'         => 'Descargas',
            'curso_id'          => 'Curso',
            'usuario_crea'      => 'Usuario Crea',
            'fecha_crea'        => 'Fecha Crea',
            'usuario_modifica'  => 'Usuario Modifica',
            'fecha_modifica'    => 'Fecha Modifica',
        ];
    }
/*
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['sluggable'] = [
            'class' => SluggableBehavior::className(),
                'attribute' => 'titulo',
                //'slugAttribute' => 'seo_slug',
        ];
        return $behaviors;
    }
*/    
    /**
     * @inheritdoc
     */
    
     public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'titulo',
                //'slugAttribute' => 'seo_slug',
            ],
//            OptimisticLockBehavior::className(),
        ];
    }
    
    
    /**
     * @inheritdoc
     */
    
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->estado           = self::ESTADO_ACTIVO;
                $this->usuario_crea     = Yii::$app->user->id;
                $this->fecha_crea       = new Expression('NOW()');
                $this->usuario_modifica = Yii::$app->user->id;
                $this->fecha_modifica   = new Expression('NOW()');
            } else {
                if ( isset( Yii::$app->user->id ) ) {
                    $this->usuario_modifica = Yii::$app->user->id;
                    $this->fecha_modifica   = new Expression('NOW()');
                }
            }
            return true;
        }
        return false;
    }
    

    /**
     * {@inheritdoc}
     */
    public static function find()
    {
        return new ArticuloQuery(get_called_class());
    }

    /**
     * Gets query for [[Categoria]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoria()
    {
        return $this->hasOne(Categoria::className(), ['id' => 'categoria_id']);
    }

    /**
     * Gets query for [[Curso]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCurso()
    {
        return $this->hasOne(Curso::className(), ['id' => 'curso_id']);
    }

    /**
     * Gets query for [[UsuarioCrea]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarioCrea()
    {
        return $this->hasOne(User::className(), ['id' => 'usuario_crea']);
    }

    /**
     * Gets query for [[UsuarioModifica]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarioModifica()
    {
        return $this->hasOne(User::className(), ['id' => 'usuario_modifica']);
    }

    /**
     * Gets query for [[Comentarios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios()
    {
        return $this->hasMany(Comentario::className(), ['articulo_id' => 'id']);
    }
    
    /**
     * cantidad de comentarios para cada artículo
     * @return \yii\db\ActiveQuery
     */
    public function getCantidadComentarios()
    {
        return $this->hasMany(Comentario::className(), ['articulo_id' => 'id'])
                    ->where("estado = " . Comentario::ESTADO_ACTIVO)
                    ->count();
    }
    
    /**
     * @return String the URL for the article detail
     */
    public function getUrl()
    {
        return BaseUrl::home() . "articulo/" . $this->slug;
    }
    
    public function getFechaTexto()
    {
        setlocale(LC_TIME, 'es_CO.UTF-8');
        //setlocale(LC_TIME, 'spa_ES');
        //setlocale(LC_TIME, 'spl_ES');
        //setlocale(LC_TIME, 'Spanish_Colombia');
        //setlocale(LC_TIME, 'es_CO.UTF-8');
//        return date('l, M j \d\e Y G:i', strtotime($this->created_at));
        return strftime("%c", strtotime($this->fecha_crea));
    }
}

controllers/ArticulosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Articulo;
use app\models\ArticuloSearch;
use yii\db\Exception;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * ArticulosController implements the CRUD actions for Articulo model.
 */
class ArticulosController extends Controller
{
    public $layout = 'adminLTE3/main';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'cambiar-estado', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['buscar'],
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Articulo models.
     * @return mixed
     */
    public function actionIndex($desde = null, $hasta = null)
    {
        if ( !\Yii::$app->user->can('articulo-listar')) {
            throw new ForbiddenHttpException();
        }
        /*
        ----------------------------------------------------
        BATCH
        ----------------------------------------------------
        $model = (new yii\db\Query)->select(['category_id'])->distinct('category_id')->from('articles');
        
        foreach ($model->each() as $key => $value) {
	    echo $value['genero'] . '<br>';
	}
        */
        
        $searchModel = new ArticuloSearch();

        if (is_null($desde) or is_null($hasta)) {
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        } else {
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams, null, $desde, $hasta);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Articulo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        
        if ( 
                !\Yii::$app->user->can('articulo-admin') and 
                !\Yii::$app->user->can('articulo-ver', ['model' => $model])
            ) {
            throw new ForbiddenHttpException();
        }
        
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Articulo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if ( !\Yii::$app->user->can('articulo-crear')) {
            throw new ForbiddenHttpException();
        }
        
        $model = new Articulo();
        $model->loadDefaultValues();
        if ($model->load(Yii::$app->request->post())) {
//            $transaction = Article::getDb()->beginTransaction();
            $transaction = Yii::$app->db->beginTransaction();

            try {
                $model->detalle = html_entity_decode($model->detalle);
                if ($model->save()) {
                    Yii::$app->session->setFlash("success", "Artículo $model->titulo creado satisfactoriamente!");
                } else {
                    $errors = '';
                    foreach ($model->getErrors() as $key => $value) {
                        foreach ($value as $row => $field) {
                            $errors .= $field . "<br>";
                        }
                    }
                    Yii::$app->session->setFlash("danger", $errors);
                    return $this->render('create', [
                                'model' => $model,
                    ]);
                }
                $transaction->commit();
                return $this->redirect(['index']);
            } catch (\Exception $e) {           // PHP 5
                $transaction->rollBack();
                throw $e;
            } catch (\Throwable $e) {            // PHP 7
                $transaction->rollBack();
                throw $e;
//          } catch(yii\db\StaleObjectException $e) {
//            Yii::$app->session->setFlash("danger", "El registro ha sido modificado por otro usuario");
//			throw $e;	// the register has been modified for multiples users
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Articulo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if ( 
                !\Yii::$app->user->can('articulo-admin') and 
                !\Yii::$app->user->can('articulo-borrar', ['model' => $model])
            ) {
            throw new ForbiddenHttpException();
        }

        if ($model->load(Yii::$app->request->post())) {

            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->detalle = html_entity_decode($model->detalle);
                if ($model->update()) {
                    Yii::$app->session->setFlash("success", "Artículo $model->titulo actualizado satisfactoriamente!");
                } else {
                    $errors = '';
                    foreach ($model->getErrors() as $key => $value) {
                        foreach ($value as $row => $field) {
                            $errors .= $field . "<br>";
                        }
                    }
                    $transaction->rollBack();
                    Yii::$app->session->setFlash("danger", $errors);
                }
                $transaction->commit();
            } catch (Exception $e) {
                Yii::$app->session->setFlash("danger", "Artículo $model->titulo no puede ser actualizado!");
                return $this->redirect(['view', 'id' => $model->id]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Articulo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        
        if ( 
                !\Yii::$app->user->can('articulo-admin') and 
                !\Yii::$app->user->can('articulo-borrar', ['model' => $model])
            ) {
            throw new ForbiddenHttpException();
        }
        
        try {
            $model->delete();
            Yii::$app->session->setFlash(
                'success', 
                Yii::t('app', "Artículo $model->titulo eliminado satisfactoriamente")
            );
        } catch(Exception $e) {
            
            if ($e->errorInfo[1] == 1451) {
                Yii::$app->session->setFlash(
                    'warning',
                    Yii::t(
                        'app',
                        'No se puede borrar el artículo porque tiene registros asociados'
                    )
                );
            } else {
                Yii::$app->session->setFlash(
                    'error',
                    Yii::t(
                        'app',
                        'Error al eliminar el registro'
                    )
                );
            }
            return $this->redirect(['index']);
        }

        return $this->redirect(['index']);
    }
    
    /**
     * Actualiza el estado de un artículo
     * Si se actualiza correctamente se redirige al index
     * @param integer $id id del artículo
     * @return mixed
     * @throws NotFoundHttpException si el registro no puede ser encontrado
     */
    public function actionCambiarEstado($id)
    {
        if ( !\Yii::$app->user->can('articulo-cambiar-estado')) {
            throw new ForbiddenHttpException();
        }
        
        $model = $this->findModel($id);
        if ($model->estado == $model::ESTADO_INACTIVO) {
            $model->estado = $model::ESTADO_ACTIVO;
        } elseif ($model->estado == $model::ESTADO_ACTIVO) {
            $model->estado = $model::ESTADO_INACTIVO;
        }
        if ($model->save()) {
            Yii::$app->session->setFlash(
                'success', 
                Yii::t('app', "Artículo $model->titulo actualizado satisfactoriamente!")
            );
        } else {
            $errors = '';
            foreach ($model->getErrors() as $key => $value) {
                foreach ($value as $row => $field) {
                    $errors .= $field . "<br>";
                }
            }

            Yii::$app->session->setFlash("danger", $errors);
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Artículos para los select
     * @param String $q artículo a buscar
     * @return Array Listado de los artículos
     */
    public function actionBuscar($q = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

views/articulos/_form.php
<?php

use app\models\Categoria;
use app\models\Curso;
use kartik\select2\Select2;
use mihaildev\ckeditor\CKEditor;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Articulo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="articulo-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'numero')->textInput(['inputType' => 'number']) ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tema')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'detalle')->widget(CKEditor::class,[
        'editorOptions' => [
            'preset' => 'basic', // basic, standard, full
            'inline' => false, // false
        ],
    ]); ?>

    <?= $form->field($model, 'resumen')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'video')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descarga')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'categoria_id')->widget(Select2::classname(), [
        'model' => $model,
        'initValueText' => isset($model->categoria_id) ? $model->categoria->categoria : '',
//                'attribute' => 'categoria_id',
        'options' => ['placeholder' => 'Busque la categoría'],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Cargando Resultados...'; }"),
            ],
            'ajax' => [
                'url' => Url::to(['categorias/buscar']),
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function (categoria) { return categoria.text; }'),
            'templateSelection' => new JsExpression('function (categoria) { return categoria.text; }'),
        ],
    ]); ?>

    <?= $form->field($model, 'etiquetas')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'curso_id')->widget(Select2::class, [
        'data' => ArrayHelper::map(Curso::find()->orderBy('curso asc')->all(), 'id', 'curso'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione ...'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/articulos/_index.php
<?php

use app\models\Articulo;
use app\models\Categoria;
use app\models\Curso;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $searchArticulo app\models\ArticuloSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
    <?= GridView::widget([
        'dataProvider' => $dataProviderArticulo,
        'filterModel' => $searchArticulo,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
//            'numero',
            [
                'attribute' => 'titulo',
                'format'    => 'raw',
                'value'     => function($data){
                    return Html::a(
                        $data->titulo,
                        Yii::getAlias('@web') . '/articulo/' . $data->slug,
                        [
                            'target'    => '_blank',
                            'title'     => 'Ver post',
                        ]
                    );
                }
            ],
//            'slug',
//            'tema',
            //'detalle:ntext',
            //'resumen',
            //'video',
            //'descarga',
            [
                'attribute' => 'categoria_id',
                'value'     => 'categoria.categoria',
                'format'    => 'raw',
                'filter'    => Select2::widget([
                    'model' => $searchArticulo,
                    'attribute' => 'categoria_id',
                    'data' => ArrayHelper::map(Categoria::find()->orderBy('categoria asc')->all(), 'id', 'categoria'),
                    'options' => ['placeholder' => 'Seleccione...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]),
            ],
            //'etiquetas',
            //'estado',
            [
                'attribute' => 'vistas',
//                'width' => '150px',
//                'hAlign' => 'right',
                'format' => ['decimal', 0],
                'pageSummary' => true,
                'pageSummaryFunc' => GridView::F_AVG
            ],
            'cantidadComentarios',
            [
                'attribute' => 'descargas',
//                'width' => '150px',
//                'hAlign' => 'right',
                'format' => ['decimal', 0],
                'pageSummary' => true,
                'pageSummaryFunc' => GridView::F_AVG
            ],
            [
                'attribute' => 'curso_id',
                'value'     => 'curso.curso',
                'format'    => 'raw',
                'filter'    => Select2::widget([
                    'model' => $searchArticulo,
                    'attribute' => 'curso_id',
                    'data' => ArrayHelper::map(Curso::find()->orderBy('curso asc')->all(), 'id', 'curso'),
                    'options' => ['placeholder' => 'Seleccione...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]),
            ],
            [
                'attribute'     => 'usuario_crea',
                'value'         => 'usuarioCrea.name',
            ],
            //'fecha_crea',
//            [
//                'attribute'     => 'usuario_modifica',
//                'value'         => 'usuarioModifica.name',
//            ],
            //'fecha_modifica',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete} {cambiar-estado}',
                'buttons' => [
                    'cambiar-estado' => function ($url, $model, $key) {
                        if ($model->estado == Articulo::ESTADO_INACTIVO) {
                            return Html::a('<span class="glyphicon glyphicon-thumbs-up"></span>', $url,
                                [ 'title' => Yii::t('app', 'Activar este artículo'), ]
                            );
                        } elseif ($model->estado == Articulo::ESTADO_ACTIVO) {
                            return Html::a('<span class="glyphicon glyphicon-thumbs-down"></span>', $url,
                                [ 'title' => Yii::t('app', 'Inactivar este artículo'), ]
                            );
                        }
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url,
                            [ 'title' => Yii::t('app', 'Actualizar'), ]
                        );
                    },
//                    'delete' => function ($url, $model) {
//                          return Html::a(
//                              "<button type='button' class = 'btn btn-danger btn-circle' >
//                                <i class='fa fa-trash' aria-hidden='true'></i>
//                              </button>", ["delete", "id" => $model->id], [
//                              'title' => 'Eliminar',
//                              'data-method'   => 'POST',
//                              'data-confirm'  => 'Desea eliminar este registro?',
//                          ]);
//                    },
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        return yii\helpers\Url::to(['articulos/view', 'id' => $key]);
                    } elseif ($action === 'cambiar-estado') {
                        return yii\helpers\Url::to(['articulos/cambiar-estado', 'id' => $key]);
                    } elseif ($action == 'update') {
                        return yii\helpers\Url::to(['articulos/update/', 'id' => $key]);
                    } elseif ($action === 'delete') {
                        return yii\helpers\Url::to(['articulos/delete/', 'id' => $key]);
                    }
                }
            ],
        ],
        'export'    => [
            'label'     => 'Exportar',
            'messages'  => [
                'confirmDownload'   => 'De acuerdo para proceder',
            ],
//            'showConfirmAlert'  => false,
        ],
        'exportConfig' => [
//            GridView::HTML => [
//            ],
            GridView::CSV => [
            ],
//            GridView::TEXT => [
//            ],
            GridView::EXCEL => [
                'label' => ( 'XLS'),
                'iconOptions' => ['class' => 'text-success'],
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => ('archivoDeBlonder413'),
                'alertMsg' => ( 'El archivo de excel se va descargar.'),
                'options' => ['title' => ( 'Excel')],
                'mime' => 'application/vnd.ms-excel',
                'config' => [
                    'worksheet' => ( 'ExportWorksheet'),
                    'cssFile' => '',
                ]
            ],
            GridView::PDF => [
            ],
//            GridView::JSON => [
//            ],
        ],
        'hover'         => true,
        'toolbar' => [
            '{toggleData}',
            '{export}',
        ],
        'toggleDataContainer' => ['class' => 'btn-group mr-2'],
        'responsive'    => true,
        'rowOptions'    => function($model){
            if ($model->estado == Articulo::ESTADO_INACTIVO) {
                return ['class' => 'danger'];
            } elseif ($model->estado == Articulo::ESTADO_ACTIVO) {
                return ['class' => 'success'];
            }
        },
        'panel'     => [
            'after'=>Html::a('<i class="fas fa-redo"></i> Limpiar Tabla', ['index'], ['class' => 'btn btn-info']),
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Crear', ['create'], ['class' => 'btn btn-success']),
            'heading' => 'Administrar Artículos',
            'type'  => GridView::TYPE_SUCCESS,
            
            
        ],
    ]); ?>

views/articulos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ArticuloSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="articulo-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'numero') ?>

    <?= $form->field($model, 'titulo') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'tema') ?>

    <?php // echo $form->field($model, 'detalle') ?>

    <?php // echo $form->field($model, 'resumen') ?>

    <?php // echo $form->field($model, 'video') ?>

    <?php // echo $form->field($model, 'descarga') ?>

    <?php // echo $form->field($model, 'categoria_id') ?>

    <?php // echo $form->field($model, 'etiquetas') ?>

    <?php // echo $form->field($model, 'estado') ?>

    <?php // echo $form->field($model, 'vistas') ?>

    <?php // echo $form->field($model, 'descargas') ?>

    <?php // echo $form->field($model, 'curso_id') ?>

    <?php // echo $form->field($model, 'usuario_crea') ?>

    <?php // echo $form->field($model, 'fecha_crea') ?>

    <?php // echo $form->field($model, 'usuario_modifica') ?>

    <?php // echo $form->field($model, 'fecha_modifica') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/articulos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Articulo */

$this->title = 'Crear Articulo';
$this->params['breadcrumbs'][] = ['label' => 'Articulos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulo-create">

    <div class='panel panel-warning'>
        <div class='panel-heading'>
            <h4><?= Html::encode($this->title) ?></h4>
        </div>
        <div class='panel-body'>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

views/articulos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Articulo */

$this->title = 'Actualizar Articulo: ' . $model->titulo;
$this->params['breadcrumbs'][] = ['label' => 'Articulos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->titulo, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="articulo-update">

    <div class='panel panel-warning'>
        <div class='panel-heading'>
            <h4><?= Html::encode($this->title) ?></h4>
        </div>
        <div class='panel-body'>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>